Change patchapp.sh to be make-based
patchapp.sh is now “make [info | ipa | deploy | debug]”

diff --git a/module/patchapp b/module/patchapp
--- a/module/patchapp
+++ b/module/patchapp
@@ -5,28 +5,31 @@
 #
 IPA="app.ipa"
 DEV_CERT_NAME="iPhone Developer"
-PRODUCT_DIR="."
+ENTITLEMENTS=".entitlements"
 TMPDIR=".patchapp.cache"
-DYLIB=".theos/latest.dylib"
+PRODUCT_DIR="." # packages
+
 COMMAND=$1
 MOBILEPROVISION=$2
+DYLIB=$3
+
+function log { echo "[+] $1"; }
+function error { echo "$1" >&2; exit 1; }
 
 #
 # Usage / syntax
 #
 function usage {
-	if [ "$2" == "" -o "$1" == "" ]; then
-		cat <<USAGE
-Usage: $0 <command> [file.mobileprovision | your.bundle.id | -w]
+	cat <<USAGE
+Usage: $0 <command> [file.mobileprovision | your.bundle.id]
 Where 'command' is one of:
 	info    - Show the information required to create a Provisioning Profile
 	          that matches the specified .ipa file
 	patch   - Inject the tweak into the specified .ipa file.
-	    	  Requires that you specify a .mobileprovision file
+			  Uses a wildcard profile if you don't specify one
 	install - Patch and deploy the app onto your device via USB
    	debug   - Like deploy, but also debug the app with LLDB
 USAGE
-	fi
 }
 
 #
@@ -34,23 +37,14 @@ USAGE
 #
 function setup_environment {
 
-	CODESIGN_NAME=`security dump-keychain login.keychain|grep "$DEV_CERT_NAME"|head -n1|cut -f4 -d \"|cut -f1 -d\"`
+	CODESIGN_NAME=`security find-certificate -c "$DEV_CERT_NAME" login.keychain | grep alis | cut -f4 -d\" | cut -f1 -d\"`
 
 	if [ "$?" != "0" ]; then
-		echo "Could not get codesign name"
-		exit 1
-	fi
-
-	DYLIB=`readlink $DYLIB`
-
-	if [ "$?" != "0" ] || [ ! -r "$DYLIB" ]; then
-		echo "Tweak dylib not found or readable. Have you run 'make' yet?"
-		exit 1
+		error "Could not get codesign name"
 	fi
 
 	if [ ! -r "$IPA" ]; then
-		echo "$IPA not found or not readable"
-		exit 1
+		error "$IPA not found or not readable"
 	fi
 
 	# setup
@@ -59,18 +53,16 @@ function setup_environment {
 	SAVED_PATH=`pwd`
 
 	# uncompress the IPA into tmpdir
-	echo '[+] Unpacking the .ipa file ('"`pwd`/$IPA"')...'
+	log "Unpacking the .ipa file (\"`pwd`/$IPA\")..."
 	unzip -o -d "$TMPDIR" "$IPA" >/dev/null 2>&1
 	if [ "$?" != "0" ]; then
-		echo "Couldn't unzip the IPA file."
-		exit 1
+		error "Couldn't unzip the IPA file."
 	fi
 
 	cd "$TMPDIR"
 	cd Payload/*.app
 	if [ "$?" != "0" ]; then
-		echo "Couldn't change into Payload folder. Wat."
-		exit 1
+		error "Couldn't change into Payload folder. Wat."
 	fi
 	APP=`pwd`
 	APP=${APP##*/}
@@ -103,8 +95,10 @@ function ipa_info {
 ==================
 1. Build your Theos tweak if you haven't already done so. Just run "make".
 2. Create a provisioning profile for this app (run "$0 info" for help)
-3. Run "$0 install file.mobileprovision" to patch and install the .ipa 
-   (you can even specify a bundle id or '-w' to use a wildcard profile)
+3. Run "$0 install <profile>" to patch and install the .ipa, replacing <profile> with:
+   	A .mobileprovision file
+   	A bundle id
+   	Or leave it blank to use a wildcard profile
 
 =====================================
 = Creating the provisioning profile =
@@ -118,12 +112,11 @@ function ipa_info {
 	b. Under "App Services" enable the following services:
 
 INFO
-	codesign -d --entitlements - "$APPDIR/$APP_BINARY" > .entitlements.xml 2>/dev/null
+	codesign -d --entitlements - "$APPDIR/$APP_BINARY" > "$ENTITLEMENTS.xml" 2>/dev/null
 	if [ "$?" != "0" ]; then
-		echo "Failed to get entitlements for $APPDIR/$APP_BINARY"
-		exit 1
+		error "Failed to get entitlements for $APPDIR/$APP_BINARY"
 	fi
-	for ent in `grep -a '<key>' .entitlements.xml`; do
+	for ent in `grep -a '<key>' "$ENTITLEMENTS.xml"`; do
 		entitlement=`echo $ent | cut -f2 -d\> | cut -f1 -d\<`
 		case $entitlement in
 			com.apple.developer.networking.vpn.api)
@@ -140,10 +133,14 @@ INFO
 				;;
 			com.apple.security.application-groups)
 				echo ">>> App Groups:"
-				for group in `dd if=.entitlements.xml bs=1 skip=8 2>/dev/null|sed -ne '/application-groups/,/<\/array/p'|grep '<string>' 2>/dev/null`; do #|tail -n1` #|cut -f2 -d\>|cut -f1 -d\<`
-					GROUP_ID=`echo $group | cut -f2 -d\>|cut -f1 -d\<`-patched
+				for group in `dd if="$ENTITLEMENTS.xml" bs=1 skip=8 2>/dev/null | sed -ne '/application-groups/,/<\/array/p' | grep '<string>' 2>/dev/null`; do #|tail -n1` #|cut -f2 -d\>|cut -f1 -d\<`
+					GROUP_ID=`echo $group | cut -f2 -d\> | cut -f1 -d\<`-patched
 					echo "    $GROUP_ID"
-				done				
+				done
+				# for group in `dd if="$ENTITLEMENTS.xml" bs=1 skip=8 2>/dev/null | sed -ne '/application-groups/,/<\/array/p' | grep '<string>' 2>/dev/null`; do #|tail -n1` #|cut -f2 -d\>|cut -f1 -d\<`
+				# 	GROUP_ID=`echo $group | cut -f2 -d\> | cut -f1 -d\<`-patched
+				# 	echo "    $GROUP_ID"
+				# done				
 				;;
 			com.apple.developer.associated-domains)
 				echo ">>> Associated Domains"
@@ -160,7 +157,7 @@ INFO
 				echo ">>> Data Protection"
 				;;
 		esac
-	done | tee .entitlements.txt
+	done | tee "$ENTITLEMENTS.txt"
 	cat <<INFO2
 
 5. Add a new Provisioning Profile
@@ -187,9 +184,9 @@ INFO
 	Note: You can't install over the top of the real application,
 	      so it must be deleted first. This only needs to be done
 	      once per patched application.
-2. Run "$0 install file.mobileprovision" as described above
-3. If "$0 install" did not work for whatever reason, use 
-   "$0 patch file.mobileprovision", and do the following
+2. Run "$0 install [file.mobileprovision | your.bundle.id]" as described above
+3. If "$0 install" did not work for whatever reason, 
+   replace "install" with "patch", and do the following
 	a. In Xcode goto Window / Devices
 	b. Under "Installed Apps" click the + button
 	c. Browse to the patched .ipa file and cross your fingers
@@ -200,18 +197,18 @@ INFO
 ===========
 Do all of the things mentioned under "What to do now", above.
 Make sure that the provisioning profile contains the correct entitlements (see above).
-Once you've installed the provisioning profile on your device, run the following command:
-    $0 patch [file.mobileprovision | your.bundle.id | -w]
+Once you have installed the provisioning profile on your device, run the following command:
+    $0 patch [file.mobileprovision | your.bundle.id]
 
 Bundle ID: $BUNDLE_ID
 Required Entitlements: 
 INFO2
-	cat .entitlements.txt
+	cat "$ENTITLEMENTS.txt"
 	exit 0
 
 	loop=0
-	for group in `dd if=.entitlements.xml bs=1 skip=8 2>/dev/null|sed -ne '/application-groups/,/<\/array/p'|grep '<string>' 2>/dev/null`; do #|tail -n1` #|cut -f2 -d\>|cut -f1 -d\<`
-		GROUP_ID=`echo $group | cut -f2 -d\>|cut -f1 -d\<`-patched
+	for group in `dd if="$ENTITLEMENTS.xml" bs=1 skip=8 2>/dev/null | sed -ne '/application-groups/,/<\/array/p' | grep '<string>' 2>/dev/null`; do #|tail -n1` #|cut -f2 -d\>|cut -f1 -d\<`
+		GROUP_ID=`echo $group | cut -f2 -d\> | cut -f1 -d\<`-patched
 		if [ $loop == 0 ]; then
 			echo -n "App Groups: "
 		else
@@ -230,133 +227,114 @@ function ipa_patch {
 
 	setup_environment
 
-	if [ "$MOBILEPROVISION" = "" ]; then
-		usage
-		exit 1
-	fi
-
 	# https://github.com/dado3212/SnapchatReloaded/blob/master/patchapp.sh
-
 	if [ ! -r "$MOBILEPROVISION" ]; then
-		# MOBILEPROVISION may be a bundle id or -w, try finding a provisioning profile that matches it
-		[ "$MOBILEPROVISION" = "-w" ] && SEARCH="Xcode iOS Wildcard App ID" || SEARCH="[^.]*\.$MOBILEPROVISION"
-		BUNDLEPROVISION="$(grep -l "<string>$SEARCH<\/string>" ~/Library/MobileDevice/Provisioning\ Profiles/*|head -n1)"
+		# MOBILEPROVISION may be a bundle id / wildcard, try finding a provisioning profile that matches it
+		[ -z "$MOBILEPROVISION" ] && SEARCH="Xcode iOS Wildcard App ID" || SEARCH="[^.]*\.$MOBILEPROVISION"
+		BUNDLEPROVISION="$(grep -l "<string>$SEARCH<\/string>" ~/Library/MobileDevice/Provisioning\ Profiles/* | head -n1)"
 
 		if [ ! -r "$BUNDLEPROVISION" ]; then # BUNDLEPROVISION can't be read
-			echo "Can't read '$MOBILEPROVISION'"
-			exit 1
+			error "Can't read '$MOBILEPROVISION'"
 		fi
 
 		MOBILEPROVISION="$BUNDLEPROVISION"
 	fi
 
 	if ! hash "optool" 2>/dev/null; then
-		echo "You need to install optool from here: https://github.com/alexzielenski/optool"
-		echo "Then add it to your PATH."
-		exit 1
+		error "Install optool and add it to your PATH: https://github.com/alexzielenski/optool"
 	fi
 
-	DEVELOPER_ID=`security dump-keychain login.keychain|grep "$DEV_CERT_NAME"|head -n1|cut -f2 -d \(|cut -f1 -d\)`
+	DEVELOPER_ID=`echo $CODESIGN_NAME | cut -f2 -d \( | cut -f1 -d\)`
 	if [ "$?" != "0" ]; then
-		echo "Error getting Apple \""$DEV_CERT_NAME"\" certificate ID."
-		exit 1
+		error "Error getting \"$DEV_CERT_NAME\" certificate ID."
 	fi
 
 	# copy the files into the .app folder
-	echo '[+] Copying .dylib dependences into "'$TMPDIR/Payload/$APP'"'
-	cp "$DYLIB" $TMPDIR/Payload/$APP/
+	log "Copying .dylib dependences into \"$TMPDIR/Payload/$APP\""
+	cp "$DYLIB" "$TMPDIR/Payload/$APP/"
 
 	# sign all of the .dylib files we're injecting into the app
-	echo '[+] Codesigning .dylib dependencies with certificate "'$CODESIGN_NAME'"'
+	log "Codesigning .dylib dependencies with certificate \"$CODESIGN_NAME\""
 	for file in "$APPDIR/${DYLIB##*/}" "$DYLIB"; do
 		echo '     '$file
 		codesign -fs "$CODESIGN_NAME" "$file" >& /dev/null
 		if [ "$?" != "0" ]; then
-			echo "Codesign failed. Have you run 'make' yet?"
-			exit 1
+			error "Codesign failed. Have you run 'make' yet?"
 		fi
 	done
 
 	# patch the app to load the new .dylib (sames a _backup file)
-	echo '[+] Patching "'$APPDIR/$APP_BINARY'" to load "'${DYLIB##*/}'"'
+	log "Patching \"$APPDIR/$APP_BINARY\" to load \"${DYLIB##*/}\""
 	if [ "$?" != "0" ]; then
-		echo "Failed to grab executable name from Info.plist. Debugging required."
-		exit 1
+		error "Failed to grab executable name from Info.plist. Debugging required."
 	fi
-	optool install -c load -p "@executable_path/"${DYLIB##*/} -t $APPDIR/$APP_BINARY >& /dev/null
+	optool install -c load -p "@executable_path/${DYLIB##*/}" -t $APPDIR/$APP_BINARY >& /dev/null
 	if [ "$?" != "0" ]; then
-		echo "Failed to inject "${DYLIB##*/}" into $APPDIR/${APP_BINARY}. Can I interest you in debugging the problem?"
-		exit 1
+		error "Failed to inject "${DYLIB##*/}" into $APPDIR/${APP_BINARY}. Can I interest you in debugging the problem?"
 	fi
 	chmod +x "$APPDIR/$APP_BINARY"
 
 	# generate the correct entitlements
-	echo '[+] Generating .entitlements.xml for developer ID '$DEVELOPER_ID
-	cat <<XML > .entitlements.xml
+	log "Generating entitlements for developer ID $DEVELOPER_ID"
+	cat <<XML > "$ENTITLEMENTS.xml"
 <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
 <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
 <plist version="1.0">
 XML
-	strings "$MOBILEPROVISION" | sed -e '1,/<key>Entitlements<\/key>/d' -e '/<\/dict>/,$d' >> .entitlements.xml
-	echo "</dict></plist>" >> .entitlements.xml
+	strings "$MOBILEPROVISION" | sed -e '1,/<key>Entitlements<\/key>/d' -e '/<\/dict>/,$d' >> "$ENTITLEMENTS.xml"
+	echo "</dict></plist>" >> "$ENTITLEMENTS.xml"
 
 	# Make sure to sign any Plugins in the app. Do NOT attempt to optimize this, the order is important!
-	echo '[+] Codesigning Plugins and Frameworks with certificate "'$CODESIGN_NAME'"'
-	for file in `ls -1 $APPDIR/PlugIns/com.*/com.*`; do
+	log "Codesigning Plugins and Frameworks with certificate \"$CODESIGN_NAME\""
+	for file in `ls -1 $APPDIR/PlugIns/com.*/com.* 2>/dev/null`; do
 		echo -n '     '
-		codesign -fs "$CODESIGN_NAME" --deep --entitlements .entitlements.xml $file
+		codesign -fs "$CODESIGN_NAME" --deep --entitlements "$ENTITLEMENTS.xml" $file
 	done
-	for file in `ls -d1 $APPDIR/PlugIns/com.*`; do
+	for file in `ls -d1 $APPDIR/PlugIns/com.* 2>/dev/null`; do
 		echo -n '     '
-		codesign -fs "$CODESIGN_NAME" --deep --entitlements .entitlements.xml $file
+		codesign -fs "$CODESIGN_NAME" --deep --entitlements "$ENTITLEMENTS.xml" $file
 	done
 
 	# re-sign Frameworks, too
-	for file in `ls -1 $APPDIR/Frameworks/*`; do
+	for file in `ls -1 $APPDIR/Frameworks/* 2>/dev/null`; do
 		echo -n '     '
-		codesign -fs "$CODESIGN_NAME" --entitlements .entitlements.xml $file
+		codesign -fs "$CODESIGN_NAME" --entitlements "$ENTITLEMENTS.xml" $file
 	done
 
 	# re-sign the .app
-	echo '[+] Codesigning the patched .app bundle with certificate "'$CODESIGN_NAME'"'
+	log "Codesigning the patched .app bundle with certificate \"$CODESIGN_NAME\""
 	cd $TMPDIR/Payload
 	echo -n '     '
-	codesign -fs "$CODESIGN_NAME" --deep --entitlements ../../.entitlements.xml $APP
+	codesign -fs "$CODESIGN_NAME" --deep --entitlements "../../$ENTITLEMENTS.xml" $APP
 	if [ "$?" != "0" ]; then
 		cd ..
-		echo "Failed to sign $APP with .entitlements.xml. You're on your own, sorry."
-		exit 1
+		error "Failed to sign $APP with entitlements. You're on your own, sorry."
 	fi
 	cd ..
 	
 	# re-pack the .ipa
-	echo '[+] Repacking the .ipa'
+	log "Repacking the .ipa"
 	rm -f "${IPA%*.ipa}-patched.ipa" >/dev/null 2>&1
 	zip -9r "${IPA%*.ipa}-patched.ipa" Payload/ >/dev/null 2>&1
 	if [ "$?" != "0" ]; then
-		echo "Failed to compress the app into a .ipa file."
-		exit 1
+		error "Failed to compress the app into a .ipa file."
 	fi
 	IPA=${IPA#../*}
 	mkdir -p "../$PRODUCT_DIR"
 	mv "${IPA%*.ipa}-patched.ipa" "../$PRODUCT_DIR/"
 	if [ "$?" != "0" ]; then
-		echo "Failed to move .ipa file into $PRODUCT_DIR."
-		exit 1
+		error "Failed to move .ipa file into $PRODUCT_DIR."
 	fi
-	echo "[+] Wrote \"${IPA%*.ipa}-patched.ipa\""
-	echo "[+] Great success!"
+	log "Wrote \"${IPA%*.ipa}-patched.ipa\""
+	log "Great success!"
 	cd - >/dev/null 2>&1
 }
 
 function ipa_deploy {
 	if ! hash "ios-deploy" 2>/dev/null; then
-		echo "You need to install ios-deploy from here: https://github.com/phonegap/ios-deploy#installation"
-		echo "Then add it to your PATH."
-		exit 1
+		error "Install ios-deploy and add it to your PATH: https://github.com/phonegap/ios-deploy#installation"
 	fi
-	ipa_patch
-	ios-deploy -$1Wb $APP
+	ios-deploy -$1Wb $TMPDIR/Payload/*.app
 }
 
 #
